"""``export-models``: train the DDA models, export them for the game, write reports/dda.md.

Inputs: a synthetic dataset directory (gen_dataset.gd, slot 0 = probed "player" with a known d),
optionally ``dda_sweep.csv`` (scripts/dda_sweep.sh) and ``dda_converge.csv``
(scripts/dda_converge.gd) in the report directory. Outputs: ``<models>/skill_estimator.json``,
``<models>/win_prob.json`` (res://data/models/), ``dda.md`` and ``dda_sweep.png``.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from brawl_analysis import markdown as md  # noqa: E402
from brawl_analysis.charts import ACCENT, MUTED, _save  # noqa: E402
from brawl_analysis.io import Dataset  # noqa: E402
from brawl_analysis.models.dda_models import (  # noqa: E402
    d_effect,
    dda_timeline,
    probe_table,
    train_estimator,
    train_win_prob_dda,
)

ESTIMATOR_FILE = "skill_estimator.json"
WIN_PROB_FILE = "win_prob.json"
SWEEP_FILE = "dda_sweep.csv"
CONVERGE_FILE = "dda_converge.csv"


def sweep_chart(sweep: pd.DataFrame, path: Path) -> Path:
    fig, ax = plt.subplots(figsize=(5.5, 3.8))
    err = [sweep["win_rate"] - sweep["ci_lo"], sweep["ci_hi"] - sweep["win_rate"]]
    ax.errorbar(
        sweep["d"],
        sweep["win_rate"],
        yerr=err,
        marker="o",
        color=ACCENT,
        capsize=3,
        label="bot(d) vs bot(0.5), 95% Wilson",
    )
    ax.axhline(0.5, color=MUTED, linestyle="--", linewidth=1)
    ax.set_xlabel("dial d")
    ax.set_ylabel("win rate")
    ax.set_ylim(0, 1)
    ax.set_title("Difficulty dial monotonicity")
    ax.legend(frameon=False, loc="upper left")
    return _save(fig, path)


def monotone(sweep: pd.DataFrame) -> bool:
    return bool(sweep.sort_values("d")["win_rate"].is_monotonic_increasing)


def export_models(ds: Dataset, models_dir: Path, report_dir: Path) -> list[Path]:
    """Train both models, write their JSON and the dda.md report; returns written paths."""
    models_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)
    probes = probe_table(ds)
    estimator = train_estimator(probes)
    win_prob = train_win_prob_dda(dda_timeline(ds))
    written = []
    for exp, name in ((estimator, ESTIMATOR_FILE), (win_prob, WIN_PROB_FILE)):
        path = models_dir / name
        path.write_text(json.dumps(exp.to_dict(), indent=1) + "\n")
        written.append(path)
    written.extend(_report(probes, estimator.metrics, win_prob, report_dir))
    return written


def _report(probes: pd.DataFrame, est: dict, win_prob, report_dir: Path) -> list[Path]:
    lines = [
        "# DDA — difficulty dial, probe skill estimator, win probability with d",
        "",
        "Generated by `python -m brawl_analysis export-models` (analysis/src/brawl_analysis/"
        "dda_report.py). Design: docs/superpowers/specs/2026-10-01-dda-probe-bots-design.md.",
        "",
    ]
    written = []
    sweep_path = report_dir / SWEEP_FILE
    if sweep_path.exists():
        sweep = pd.read_csv(sweep_path)
        written.append(sweep_chart(sweep, report_dir / "dda_sweep.png"))
        lines += [
            "## 1. Dial monotonicity (bot(d) vs bot(0.5), 1v1 classic, every character pair)",
            "",
            f"Monotonic increasing: **{monotone(sweep)}**. Source `{SWEEP_FILE}` "
            "(scripts/dda_sweep.sh).",
            "",
            "![sweep](dda_sweep.png)",
            "",
            md.table(
                sweep[
                    [
                        "d",
                        "matches",
                        "wins",
                        "losses",
                        "draws",
                        "win_rate",
                        "ci_lo",
                        "ci_hi",
                        "avg_ticks",
                    ]
                ]
            ),
            "",
        ]
    lines += [
        "## 2. Skill estimator (probe features -> d)",
        "",
        f"{est['rows']} probed matches; 5-fold CV. MAE **{est['mae']:.3f}** "
        f"(mean baseline {est['baseline_mae']:.3f}), R^2 **{est['r2']:.3f}**; 1v1 only: "
        f"MAE {_fmt(est['mae_1v1'])}, R^2 {_fmt(est['r2_1v1'])}.",
        "",
        md.table(d_effect(probes)),
        "",
    ]
    m = win_prob.metrics
    lines += [
        "## 3. Win probability with d (logistic, GDScript-exact)",
        "",
        f"{m['rows']} timeline rows, {m['matches']} matches, GroupKFold by match.",
        "",
        md.table(_metric_frame(m), index=True),
        "",
        md.table(pd.DataFrame({"feature": win_prob.features, "coef (std)": win_prob.coef})),
        "",
    ]
    converge_path = report_dir / CONVERGE_FILE
    if converge_path.exists():
        lines += [
            "## 4. DDA convergence (fixed-d player bot vs DDA bots)",
            "",
            f"Source `{CONVERGE_FILE}` (scripts/dda_converge.gd). Target band 0.45-0.60.",
            "",
            md.table(pd.read_csv(converge_path)),
            "",
        ]
    out = report_dir / "dda.md"
    out.write_text("\n".join(lines))
    return [*written, out]


def _metric_frame(m: dict) -> pd.DataFrame:
    keys = ["with_d", "without_d", "with_d_first_30s", "without_d_first_30s"]
    return pd.DataFrame({k: m[k] for k in keys if m.get(k)}).T


def _fmt(v: float | None) -> str:
    return "n/a" if v is None else f"{v:.3f}"
